"""Add description and url to schemes

Revision ID: a70c88262228
Revises: 
Create Date: 2026-09-10 21:09:33.484361

"""
from alembic import op
import sqlalchemy as sa


revision = 'a70c88262228'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemes', sa.Column('description', sa.String(), nullable=True))
    op.add_column('schemes', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemes', 'url')
    op.drop_column('schemes', 'description')
    # ### end Alembic commands ###
