"""add description and url to schemes

Revision ID: ccb59defaee0
Revises: a70c88262228
Create Date: 2026-09-10 21:26:01.620302

"""
from alembic import op
import sqlalchemy as sa


revision = 'ccb59defaee0'
down_revision = 'a70c88262228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
